---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /Users/shreyanshrai/.pyenv/shims/python3
  tasks:
    - name: Pull image
      docker_image:
        name: neogenkai/calculator:latest
        source: pull
    - name: Start docker service
      community.general.launchd:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Calculator neogenkai/calculator